### PR TITLE
Add support for other brands and device types

### PR DESCRIPTION
**Pull request by sjtrny**
[DRAFT]

This branch enables other brands and device types.

From https://github.com/radical-squared/aquatemp/issues/25

### CODE REVIEW

**Comment by elad-bar** [comment]
can you pls share the differnce of the response sending it with product id (as you have added) vs. without (originally)?
where did you find this option?

thanks

**Comment by elad-bar** [comment]
tried it locally, don't see any difference, not sure what the PR trying to acheive

**Comment by sjtrny** [comment]
> can you pls share the differnce of the response sending it with product id (as you have added) vs. without (originally)? 
> tried it locally, don't see any difference, not sure what the PR trying to acheive 

I've added the response to my examples in the issue https://github.com/radical-squared/aquatemp/issues/25.

> where did you find this option?

As I said in the issue "I have discovered by sniffing the HTTP requests from the HiTemp app".

Probably best to contain the discussion to that issue as this PR will take me longer than I originally thought as different platforms will need to be created for the different device types.

**Comment by elad-bar** [comment]
Fix should be that once extracted from the device list, you have the product id, and then use it to build the object for data,
So if another app will pop up in the future supporting such devices, we will not need to open the code to support it as well since it's dynamically extracts the product id.

Wdyt?

As for the discussion, @radical-squared can you pls enable this feature?

**Comment by sjtrny** [comment]
> Fix should be that once extracted from the device list

That's part of the problem. It seems for my device (a hot water heater), the device list is empty. But when specifying the product id the device id is returned from the device list. I'm not sure why 🤷‍♂️.

**Comment by mstrempel** [comment]
Hi all, 

think I am having the same issue here. No devices in the device list. I use a HydroPro Heat Pump connected to the Wifi Unit. 

How can I determine my Product ID. Do I need to sniff the HTTP traffic of my phone which then connects via the AquaTemp app?

`2023-05-31 11:25:43.502 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Request to /cloudservice/api/app/user/login.json, Result: {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': {'role_name': 'User', 'user_type': 'Customer', 'user_id': 'xxxxxxxxxxxxx', 'user_name': 'xxxxx.xxxxx@xxxxx.com', 'nick_name': 'YYYYYY', 'roleName': 'User', 'x-token': 'ZZZZZZZZZZZZZZZZZZ', 'real_name': None}, 'is_reuslt_suc': True}
2023-05-31 11:25:44.423 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Request to /cloudservice/api/app/device/deviceList.json, Result: {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': [], 'is_reuslt_suc': True}
2023-05-31 11:25:44.423 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_api] Finished discovering devices, Data: {}
2023-05-31 11:25:44.423 DEBUG (MainThread) [custom_components.aqua_temp.managers.aqua_temp_coordinator] Finished fetching Aqua Temp data in 0.000 seconds (success: True)
2023-05-31 11:25:44.424 INFO (MainThread) [custom_components.aqua_temp] Finished loading integration
2023-05-31 11:25:44.424 DEBUG (MainThread) [custom_components.aqua_temp] Loading platforms: [<Platform.SELECT: 'select'>, <Platform.BINARY_SENSOR: 'binary_sensor'>, <Platform.CLIMATE: 'climate'>, <Platform.SENSOR: 'sensor'>]
2023-05-31 11:25:44.754 DEBUG (MainThread) [custom_components.aqua_temp.select] Setting up sensor entities: []
2023-05-31 11:25:44.755 DEBUG (MainThread) [custom_components.aqua_temp.binary_sensor] Setting up binary sensor entities: []
2023-05-31 11:25:44.755 DEBUG (MainThread) [custom_components.aqua_temp.sensor] Setting up sensor entities: []
2023-05-31 11:25:45.204 DEBUG (MainThread) [custom_components.aqua_temp.climate] Setting up climate entities: []
2023-05-31 11:25:45.370 INFO (MainThread) [custom_components.aqua_temp] Finished loading components`

**Comment by elad-bar** [comment]
I found out that in the mobile app of Aqua Temp there are 4 product ids, will try to add them to request

**Comment by mstrempel** [comment]
Looked in my app, the device Id out of the app is as shown in the pic. Maybe this helps 

IMG_6177

**Comment by sjtrny** [comment]
> Looked in my app, the device Id out of the app is as shown in the pic. Maybe this helps

Where in your app is this? I can’t locate it in the HiTemp app.

**Comment by elad-bar** [comment]
Following the information you have provided, I ran sniffing on all the actions,
seems that there are 5 product Ids:
```python
SUPPORTED_PRODUCT_ID = [
    "1132174963097280512",
    "1186904563333062656",
    "1158905952238313472",
    "1442284873216843776",
    "1548963836789501952",
]
```

in addition, there are 3 API calls to load devices:
```
LIST_REGISTERED_DEVICES = "device/deviceList.json"
LIST_SHARED_APPECT_DEVICES = "device/getMyAppectDeviceShareDataList.json"
LIST_SHARED_TOBE_DEVICES = "device/getMyTobeDeviceShareDataList.json"
```

each of them requires additional parameters on top of product Ids - to_user (for shared devices), page size (if needed - 999) and page index (if needed - 1).

hope that this is the full change required, will add it to next version (v3.0.3) with credits to you.

btw, the image you have attached present the device Id not product Id, once will push my code, you will be able to run it via python CLI locally to extract all the parameters.

**Comment by elad-bar** [comment]
closing as the solution was broader than supporting 2 products, credits added as part of the release

thanks!

**Pull request closed without merging**
