### PR TITLE
Update climate.py

### PR DESCRIPTION
**Pull request by galletn**
added 
"T06" Exhaust temp
"T07" Compressor current detect (Amps used)
"T12" target fan speed
"T14" inverter plate AC voltage (Volts used)

This will allow to calculate current power consumption Volts * Amps = Watts

### CODE REVIEW

**Comment by galletn** [comment]
update to extra_state_attributes since device_state_attributes is deprecated as of 2022.4

**Comment by ludwich** [comment]
This is useful info i really need. IN/OUT heat is needed please approve

**Comment by galletn** [comment]
thanks @ludwich here a snipet of what I did with it so far 👍 

image

**Comment by ludwich** [comment]
I love it. Can you please merge ;)
Used your code but cant reach the new attributes. New to HA so can you please show me your settings in configuration?

**Comment by ludwich** [comment]
Do you need to add someting to config? Only get 1 entity from your branch as well.

**Comment by galletn** [comment]
@ludwich sorry for the late reply!

If you want to show them on your dashboards you can do that by code bellow. Other option is to make sensors from it in your config.

_**card code:**_

```
type: entities
header:
  type: picture
  image: /local/pool.jpg
entities:
  - entity: input_boolean.pool_season
  - type: attribute
    entity: climate.gpool
    name: Outside Temperature
    attribute: ambient_temperature
    suffix: °c
    icon: mdi:thermometer-lines
  - type: attribute
    entity: climate.gpool
    name: Water Temperature
    attribute: current_temperature
    suffix: °c
    icon: mdi:coolant-temperature
  - type: attribute
    entity: climate.gpool
    name: Water Inlet Temperature
    attribute: inlet_temperature
    suffix: °c
    icon: mdi:thermometer-chevron-down
  - type: attribute
    entity: climate.gpool
    name: Water Outlet Temperature
    attribute: outlet_temperature
    suffix: °c
    icon: mdi:thermometer-chevron-up
  - type: attribute
    entity: climate.gpool
    name: Coil Temperature
    attribute: coil_temperature
    suffix: °c
    icon: mdi:hydraulic-oil-temperature
  - type: attribute
    entity: climate.gpool
    name: Error Status
    attribute: is_fault
    icon: mdi:thermometer-alert
  - type: attribute
    entity: climate.gpool
    name: Error Text
    attribute: fault
    icon: mdi:thermometer-alert
  - entity: sensor.pool_heating_current
  - entity: sensor.pool_heating_current_consumption
  - entity: sensor.pool_heating_voltage
  - entity: sensor.pool_heating_energy
  - entity: sensor.energy_daily_pool_heating
    name: Pool Heating Energy Today
  - entity: sensor.energy_monthly_pool_heating
    name: Pool Heating Energy This Month
  - entity: sensor.energy_yearly_pool_heating
    name: Pool Heating Energy This Year
title: Pool Status
state_color: false

```

**_Config code for sensors:_**

```
template:
      
  - sensor:
      - name: Pool Heating Current
        unit_of_measurement: 'A'
        state: >- 
          {{ state_attr('climate.gpool', 'codes')[26].value }}
        state_class: measurement
        device_class: power
        
  - sensor:
      - name: Pool Heating Voltage
        unit_of_measurement: 'V'
        state: >- 
          {{ state_attr('climate.gpool', 'codes')[28].value }}
        state_class: measurement
        device_class: power
        
  - sensor:
      - name: Pool Heating Current Consumption
        unit_of_measurement: 'W'
        state: >- 
          {{ (state_attr('climate.gpool', 'codes')[28].value|float) * (state_attr('climate.gpool', 'codes')[26].value|float) }}
        state_class: measurement
        device_class: power
```
        

````
utility_meter:
  energy_daily_pool_heating:
    source: sensor.pool_heating_energy
    cycle: daily
    
  energy_monthly_pool_heating:
    source: sensor.pool_heating_energy
    cycle: monthly
    
  energy_yearly_pool_heating:
    source: sensor.pool_heating_energy
    cycle: yearly
 
sensor:
    - platform: integration
      source: sensor.pool_heating_current_consumption
      name: pool heating energy
      unit_prefix: k
      round: 2
      method: left
````

**Pull request merged**
